[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/nuclio/logger"

[[constraint]]
  branch = "master"
  name = "github.com/nuclio/zap"

[[override]]
  name = "github.com/pavius/zap"
  branch = "nuclio"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/v3io/v3io-go-http"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "3.3.3"

[prune]
  go-tests = true
  unused-packages = true
